# Generated by Django 4.2.27 on 2026-01-06 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_teammember_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('is_sent_to_telegram', models.BooleanField(default=False, verbose_name='Отправлено в Telegram')),
                ('telegram_error', models.TextField(blank=True, null=True, verbose_name='Ошибка отправки в Telegram')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
