# Generated by Django 4.2.27 on 2026-01-06 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chat_id', models.CharField(help_text='Уникальный идентификатор чата в Telegram', max_length=100, unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, help_text='Username пользователя в Telegram (если указан)', max_length=200, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя в Telegram', max_length=200, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя в Telegram', max_length=200, null=True, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, help_text='Получает ли пользователь уведомления', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Подписчик Telegram',
                'verbose_name_plural': 'Подписчики Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id'], name='landing_tel_chat_id_30f946_idx'), models.Index(fields=['is_active'], name='landing_tel_is_acti_fd79c9_idx')],
            },
        ),
    ]
